#ifndef GUARD_CONSTANTS_CONDITION_COACH_H
#define GUARD_CONSTANTS_CONDITION_COACH_H

#define CONDITION_COACH_PARTY_ALL PARTY_SIZE

enum ConditionCoachChoice
{
    CONDITION_COACH_CHOICE_BURN,
    CONDITION_COACH_CHOICE_POISON,
    CONDITION_COACH_CHOICE_PARALYSIS,
    CONDITION_COACH_CHOICE_REST_WAKE,
    CONDITION_COACH_CHOICE_CLEAR,
    CONDITION_COACH_CHOICE_EXIT,
};

enum ConditionCoachResult
{
    CONDITION_COACH_RESULT_APPLIED,
    CONDITION_COACH_RESULT_CANCELLED,
    CONDITION_COACH_RESULT_EGG,
    CONDITION_COACH_RESULT_FAINTED,
    CONDITION_COACH_RESULT_ALREADY_STATUS,
    CONDITION_COACH_RESULT_ALREADY_CLEAR,
    CONDITION_COACH_RESULT_INVALID_CHOICE,
    CONDITION_COACH_RESULT_LOCKED,
    CONDITION_COACH_RESULT_NO_ELIGIBLE,
    CONDITION_COACH_RESULT_PARTY_READY,
};

enum ConditionCoachHint
{
    CONDITION_COACH_HINT_NONE,
    CONDITION_COACH_HINT_CURING_ITEM,
    CONDITION_COACH_HINT_GUTS,
    CONDITION_COACH_HINT_MARVEL_SCALE,
    CONDITION_COACH_HINT_QUICK_FEET,
    CONDITION_COACH_HINT_POISON_HEAL,
    CONDITION_COACH_HINT_TOXIC_BOOST,
    CONDITION_COACH_HINT_FLARE_BOOST,
    CONDITION_COACH_HINT_MAGIC_GUARD,
    CONDITION_COACH_HINT_STATUS_MAY_SLIP,
    CONDITION_COACH_HINT_REST_WAKE,
    CONDITION_COACH_HINT_CLEAR,
};

enum ConditionCoachSignal
{
    CONDITION_COACH_SIGNAL_NONE            = 0,
    CONDITION_COACH_SIGNAL_CURING_ITEM     = 1 << 0,
    CONDITION_COACH_SIGNAL_GUTS            = 1 << 1,
    CONDITION_COACH_SIGNAL_MARVEL_SCALE    = 1 << 2,
    CONDITION_COACH_SIGNAL_QUICK_FEET      = 1 << 3,
    CONDITION_COACH_SIGNAL_POISON_HEAL     = 1 << 4,
    CONDITION_COACH_SIGNAL_TOXIC_BOOST     = 1 << 5,
    CONDITION_COACH_SIGNAL_FLARE_BOOST     = 1 << 6,
    CONDITION_COACH_SIGNAL_MAGIC_GUARD     = 1 << 7,
    CONDITION_COACH_SIGNAL_STATUS_MAY_SLIP = 1 << 8,
    CONDITION_COACH_SIGNAL_REST_WAKE       = 1 << 9,
    CONDITION_COACH_SIGNAL_CLEAR           = 1 << 10,
};

#endif // GUARD_CONSTANTS_CONDITION_COACH_H
