#ifndef GUARD_CONSTANTS_WILD_HELD_ITEM_BROKER_H
#define GUARD_CONSTANTS_WILD_HELD_ITEM_BROKER_H

enum WildHeldItemBrokerCategory
{
    WILD_HELD_ITEM_BROKER_CATEGORY_HELD_GEAR,
    WILD_HELD_ITEM_BROKER_CATEGORY_ONE_USE_HOLDS,
    WILD_HELD_ITEM_BROKER_CATEGORY_TYPE_BOOSTS,
    WILD_HELD_ITEM_BROKER_CATEGORY_EVOLUTION_FORM,
    WILD_HELD_ITEM_BROKER_CATEGORY_MEDICINE,
    WILD_HELD_ITEM_BROKER_CATEGORY_RESOURCES,
    WILD_HELD_ITEM_BROKER_CATEGORY_ALL,
    WILD_HELD_ITEM_BROKER_CATEGORY_EXIT,
    WILD_HELD_ITEM_BROKER_CATEGORY_COUNT,
};

#define WILD_HELD_ITEM_BROKER_CATEGORY_FILTER_COUNT WILD_HELD_ITEM_BROKER_CATEGORY_ALL

#define WILD_HELD_ITEM_BROKER_MASK_HELD_GEAR      (1u << WILD_HELD_ITEM_BROKER_CATEGORY_HELD_GEAR)
#define WILD_HELD_ITEM_BROKER_MASK_ONE_USE_HOLDS  (1u << WILD_HELD_ITEM_BROKER_CATEGORY_ONE_USE_HOLDS)
#define WILD_HELD_ITEM_BROKER_MASK_TYPE_BOOSTS    (1u << WILD_HELD_ITEM_BROKER_CATEGORY_TYPE_BOOSTS)
#define WILD_HELD_ITEM_BROKER_MASK_EVOLUTION_FORM (1u << WILD_HELD_ITEM_BROKER_CATEGORY_EVOLUTION_FORM)
#define WILD_HELD_ITEM_BROKER_MASK_MEDICINE       (1u << WILD_HELD_ITEM_BROKER_CATEGORY_MEDICINE)
#define WILD_HELD_ITEM_BROKER_MASK_RESOURCES      (1u << WILD_HELD_ITEM_BROKER_CATEGORY_RESOURCES)

#endif // GUARD_CONSTANTS_WILD_HELD_ITEM_BROKER_H
